name: mining-flasktemp
version: '1.0.0'
summary: flaskapp
description: |
  This is a very simple snap that displays a message on webpage server via python flask.
  If the IP address of the machine is 192.168.X.X then, from the same network you can access it in 5000 port. Like, http://192.168.X.X:5000
base: core18 
confinement: strict
assumes: [command-chain]

apps:
  #mining:
   #  command: mining.py
   #  daemon: simple
   #  restart-condition: never
    
  mining-flasktemp:
    command: flasktemp.py 
    command-chain: [snap/command-chain/mining.py]
    daemon: simple
    restart-condition: never
    plugs: [network-bind]
    environment:
      FLASK_APP: flasktemp.py
    #before: [mining]
      
parts:
  mining-flasktemp:
    plugin: python
    python-version: python3
    source: .
    python-packages : [flask]

